(module main racket
  
  (require "datatype.rkt")
  (require "interpreter.rkt")
  (require "parser.rkt")
  (require "store.rkt")

  (define (main pgm-string)
    (run pgm-string)
    )

  (main "a=[1,2,3,4]; for i in a: if i == 2: print(i); continue; else: print(23);; print(999); ; for i in a: print(i);;")
  (displayln "")                       
  (main "a=[4,3,True];print(a,4); for i in a: b = i; print(b); ; print(b); pass; a = True * False; print(a);")
  (displayln "")
  (main "l1=[1,2];l2=[3,4];l3=l1+l2;print(l3);")
  (displayln "")
  (main "n1=1;print(n1);n2=-n1;print(n2);n3=+n1;print(n3);n4=-n2;print(n4);")
  (displayln "")
  (main "a=1/2;print(a);")
  (displayln "")
  (main "print(1);pass;print(2);")
  (displayln "")
  (main "le1=0*2;print(le1);le2=False*True;print(le2);")
  (displayln "")
  (main "a=5;if a == 6 : print(1);else:print(2);;")
  (displayln "")
  (evaluate-file "../sample/list.rktpy")
  (displayln "")
  (evaluate-file "../sample/for.rktpy")
  (displayln "")
  (evaluate-file "../sample/function.rktpy")
  (displayln "")
  (evaluate-file "../sample/fib.rktpy")
  (displayln "")
  (evaluate-file "../sample/return.rktpy")
  )            
