(module main racket
  
  (require "datatype.rkt")
  (require "interpreter.rkt")
  (require "parser.rkt")
  (require "store.rkt")

  (provide run)

  (define (run pgm-string)
    (define py-lexer (lex-this python-lexer (open-input-string pgm-string)))
    (begin (initialize-store!)
           (let ((parser-res (python-parser py-lexer)))
              (value-of-program parser-res))
              ;parser-res)
           )
    )

  (run "a=[4,3,True];print(a,4); for i in a: b = i; print(b); ; print(b); pass; a = True * False; print(a);")
  (displayln "")
  (run "l1=[1,2];l2=[3,4];l3=l1+l2;print(l3);")
  (displayln "")
  (run "n1=1;print(n1);n2=-n1;print(n2);n3=+n1;print(n3);n4=-n2;print(n4);")
  (displayln "")
  (run "a=1/2;print(a);")
  (displayln "")
  (run "print(1);pass;print(2);")
  (displayln "")
  (run "le1=0*2;print(le1);le2=False*True;print(le2);")
  )             
